-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:3306
-- Généré le : mar. 13 avr. 2021 à 21:37
-- Version du serveur :  5.7.24
-- Version de PHP : 7.4.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `autocompletion`
--

-- --------------------------------------------------------

--
-- Structure de la table `sportifs`
--

CREATE TABLE `sportifs` (
  `id` int(11) NOT NULL,
  `nom` varchar(255) NOT NULL,
  `prénom` varchar(255) NOT NULL,
  `bio` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `sportifs`
--

INSERT INTO `sportifs` (`id`, `nom`, `prénom`, `bio`) VALUES
(1, 'Federer', 'Roger', 'Roger Federer, né le 8 août 1981 à Bâle, est un joueur de tennis suisse. Joueur professionnel depuis 1998, il a occupé durant 310 semaines la première place du classement mondial de tennis ATP World Tour, et détient le record de 237 semaines consécutives, soit quatre ans et 199 jours, à ce rang, ainsi que le record de la plus longue période entre sa première et son ultime accession à la tête de ce classement, quatorze ans, du 2 février 2004 au 24 juin 2018. Federer co-détient avec Rafael Nadal le record masculin de 20 victoires dans les tournois du Grand Chelem. Il a terminé l\'année calendaire à la première place mondiale à cinq reprises, en 2004, 2005, 2006, 2007 et 2009, et a été sacré champion du monde par l\'ITF au terme de ces mêmes saisons. Il est médaillé d\'or en double messieurs avec Stanislas Wawrinka aux Jeux olympiques de Pékin 2008 puis vice-champion olympique en simple à Londres en 2012. Enfin, en 2014, il remporte la Coupe Davis avec l\'équipe de Suisse 1.'),
(2, 'Djokovic', 'Novak', 'Novak Djokovic ou Novak Đoković (serbe : Новак Ђоковић, prononcé [ˈnɔ.vaːk ˈd͡ʑɔː.kɔ.vit͡ɕ] Écouter)N 1, né le 22 mai 1987 à Belgrade, est un joueur de tennis serbe, professionnel depuis 2003.\r\n\r\nConsidéré comme l\'un des plus grands joueurs de tennis de tous les temps7,8,9, Novak Djokovic a remporté 82 titres en simple sur le circuit ATP, dont 18 tournois du Grand Chelem, 5 Masters et 36 Masters 1000, détenant ainsi le record de titres dans cette catégorie. En 2018, il remporte le Masters de Cincinnati, devenant ainsi le seul joueur de l\'histoire du tennis à avoir remporté les 9 tournois de cette catégorie en simple10. Deux ans plus tard, il réédite sa victoire au Masters de Cincinnati — délocalisé à New York pour cause de pandémie de Covid-19 — et devient le premier et unique joueur de l\'histoire à avoir réalisé le Career Golden Masters à deux reprises, ayant remporté au moins deux fois chacun des 9 Masters 1000. En 2021, il s\'adjuge l\'Open d\'Australie pour la neuvième fois, ce qui fait de lui l\'unique recordman de titres dans ce tournoi majeur. Il remporte la médaille de bronze aux Jeux olympiques en 2008, la Coupe Davis avec l\'équipe de Serbie en 2010 et la première édition de l\'ATP Cup avec la Serbie en 2020. Vainqueur de tous les tournois du Grand Chelem, de tous les Masters 1000 et du Masters, Djokovic possède l\'un des palmarès les plus complets de l\'ère Open. Seule la médaille d\'or olympique lui manque encore.'),
(3, 'Agassi', 'Andre', 'Andre Agassi, né le 29 avril 1970 à Las Vegas, est un joueur de tennis américain, professionnel de 1986 à 2006.\r\n\r\nConsidéré comme l\'un des plus grands joueurs de tous les temps 1,2,3, il a remporté 60 titres en simple sur le circuit ATP, dont dix titres majeurs, incluant huit titres du Grand Chelem, un Masters et un titre olympique ; ainsi que dix-sept Masters 1000.\r\n\r\nAgassi est le seul joueur de l\'histoire à avoir remporté les sept titres les plus prestigieux du tennis en simple messieurs : les quatre tournois du Grand Chelem, la médaille d\'or olympique, le Masters et la Coupe Davis. Il est aussi le premier à s\'être imposé dans les quatre tournois du Grand Chelem sur quatre surfaces différentes (gazon, terre battue et deux types de surface dure), ce que seuls Roger Federer, Rafael Nadal et Novak Djokovic ont réussi depuis. Il est également le seul avec Rafael Nadal à avoir réalisé le « Grand Chelem doré » (victoires dans les quatre tournois majeurs et aux Jeux) en carrière.'),
(4, 'Nadal', 'Rafael', 'Rafael Nadal est un joueur de tennis espagnol, professionnel depuis 2001, né le 3 juin 1986 à Manacor, sur l\'île de Majorque, dans l\'archipel des Baléares.\r\n\r\nIl est considéré par de nombreux spécialistes comme le meilleur joueur sur terre battue de l\'histoire du tennis1,2,3, établissant en effet des records majeurs, et l\'un des meilleurs joueurs de simple de tous les temps4,5,6,7. Il a remporté vingt tournois du Grand Chelem (un record qu\'il co-détient avec Roger Federer) et est le seul joueur à avoir remporté treize titres en simple dans un de ces quatre tournois majeurs : à Roland-Garros où il s\'est imposé de 2005 à 2008, de 2010 à 2014, puis de 2017 à 2020. À l\'issue de l\'édition 2020, il présente un bilan record de 100 victoires pour deux défaites dans ce tournoi parisien. Il a remporté également le tournoi de Wimbledon en 2008 et 2010, l\'Open d\'Australie 2009 et l\'US Open 2010, 2013, 2017 et 2019. Il est ainsi le septième joueur de l\'histoire du tennis à réaliser le « Grand Chelem en carrière » en simple. À ce titre, Rafael Nadal est le troisième joueur et le plus jeune à s\'être imposé durant l\'ère Open dans les quatre tournois majeurs sur quatre surfaces différentes, performance que seuls Roger Federer, Andre Agassi et Novak Djokovic ont accomplie.'),
(5, 'Kyrgios', 'Nick', 'Nick Kyrgios, né le 27 avril 1995 à Canberra, est un joueur de tennis australien1.\r\n\r\nIl remporte l\'Open d\'Australie 2013 junior en simple et en double. Professionnel depuis 2013, il a remporté six titres sur le circuit ATP. Ses meilleurs résultats en tournoi du Grand Chelem sont un quart de finale à Wimbledon en 2014 et un quart de finale à l\'Open d\'Australie en 2015. Il est donc le premier Australien à avoir atteint les quarts de finale de l\'Open d\'Australie depuis Lleyton Hewitt en 20052.\r\n\r\nIl joue en Coupe Davis avec l\'Australie depuis 2013. Il remporte la Hopman Cup avec Daria Gavrilova en 2016.'),
(6, 'Gasquet', 'Richard', 'Richard Gasquet, né le 18 juin 1986 à Béziers (Hérault), est un joueur français de tennis professionnel1.\r\n\r\nJoueur précoce, il devient no 1 mondial chez les juniors en 2002, année où il passe professionnel. Quinze fois titré en simple sur le circuit ATP pour un total de 31 finales, il a atteint la septième place mondiale et a participé aux Masters de fin d\'année en 2007 et 2013. Ses meilleures performances en tournoi du Grand Chelem sont trois demi-finales, à Wimbledon en 2007 et 2015 et à l\'US Open en 2013. Par équipe, Richard Gasquet fait partie de l\'équipe de France de Coupe Davis depuis 2005, qu\'il finit par remporter en 2017. En double, il a remporté deux titres ATP, le titre en double mixte à Roland-Garros en 2004 avec Tatiana Golovin et la médaille de bronze lors des Jeux olympiques de Londres en 2012 aux côtés de Julien Benneteau2. Associé à Kristina Mladenovic, il a aussi gagné la coupe Hopman en 2017.'),
(7, 'Wawrinka', 'Stanislas', 'Stanislas Wawrinka, également connu sous la forme abrégée Stan Wawrinka1, né le 28 mars 1985 à Lausanne, est un joueur de tennis suisse, professionnel depuis 2002.\r\n\r\nIl remporte seize titres en simple sur le circuit ATP, dont trois tournois du Grand Chelem : l\'Open d\'Australie en 2014, Roland-Garros en 2015 et l\'US Open en 2016. Il est le deuxième joueur suisse à remporter un tournoi du Grand Chelem après Roger Federer, avec qui il remporte la médaille d\'or en double aux Jeux olympiques de 2008 à Pékin et la Coupe Davis 2014 sous les couleurs de la Suisse.'),
(8, 'Roddick', 'Andy', 'Andrew Stephen Roddick, dit Andy Roddick, né le 30 août 1982 à Omaha dans le Nebraska, est un joueur de tennis américain.\r\n\r\nProfessionnel de 2000 à 2012, il a remporté trente-deux titres en simple messieurs sur le circuit ATP, dont l\'US Open en 2003, ainsi que cinq Masters 1000.\r\n\r\nIl atteint son meilleur classement en 2003 à la première place mondiale, qu\'il occupera pour un total de treize semaines cumulées. Cette même année, il s\'impose consécutivement au Masters 1000 du Canada, à Cincinnati et à l\'US Open, devenant l\'un des rares athlètes à réaliser le triplé américain, et achève la saison au sommet du classement avant d\'être sacré champion du monde par l\'ITF et joueur de l\'année ATP.\r\n\r\nTriple finaliste du tournoi de Wimbledon en 2004, 2005 et 2009, Roddick s\'est également illustré à l\'Open d\'Australie, où il a atteint les demi-finales à quatre reprises, ainsi qu\'au Masters de fin d\'année, avec trois demi-finales pour six participations. Il a été membre du top dix mondial neuf saisons consécutives, de 2002 à 2010.'),
(9, 'Sampras', 'Pete', 'Petros Sampras, dit Pete Sampras, né le 12 août 1971 à Washington, est un joueur de tennis américain.\r\n\r\nProfessionnel de 1988 à 2002, il a remporté 64 titres en simple sur le circuit ATP, dont 21 titres majeurs, incluant 14 tournois du Grand Chelem, 5 Masters, et 2 Coupes du Grand Chelem.\r\n\r\nAyant achevé six saisons au premier rang mondial entre 1993 et 1998, ce chiffre constitue un record dans l\'ère Open qu\'il détient en compagnie du Serbe Novak Djokovic. Il a occupé la place de numéro un pendant un total de 286 semaines ce qui le situe en troisième position derrière Djokovic et Roger Federer. Il s\'est particulièrement illustré à Wimbledon, où il a remporté tout comme William Renshaw sept titres, ce qui a constitué un record jusqu\'en 2017 et la huitième victoire de Roger Federer. En 1992 et 1995, il remporte la Coupe Davis avec l\'équipe des États-Unis, puis égale le record de cinq victoires aux Masters d\'Ivan Lendl en 1999, record battu par la suite par Federer. Il clôt sa carrière par une ultime victoire à l’US Open 2002, obtenue face à son meilleur rival Andre Agassi.'),
(10, 'Becker', 'Boris', 'Boris Franz Becker, né à Leimen (Bade-Wurtemberg) le 22 novembre 1967, est un joueur de tennis allemand professionnel. Il a remporté six tournois du Grand Chelem, Wimbledon en 1985, 1986 et 1989, l\'US Open en 1989 et l\'Open d\'Australie en 1991 et 1996. Il a également remporté trois fois les Masters de fin d\'année en 1988, 1992 et 1995, ainsi que deux fois la Coupe Davis en 1988 et 1989. Il fait sensation quand il remporte son premier Wimbledon à 17 ans en 1985, et gagne un surnom « Boum-Boum Becker ».\r\n\r\nSa surface de prédilection était la moquette sur laquelle il a remporté plus de la moitié de ses 49 titres en simple.\r\n\r\nIl est le second joueur (après Rafael Nadal) ayant gagné le plus grand nombre de matchs contre un no 1 mondial avec 19 victoires, notamment contre Ivan Lendl, Stefan Edberg et Pete Sampras. Il est l\'un des dix joueurs avec Björn Borg, Rafael Nadal, Roger Federer, Pete Sampras, Novak Djokovic, Jimmy Connors, Ivan Lendl, John McEnroe et Andre Agassi à avoir un ratio de plus de 80 % de victoires en Grand Chelem. Il a remporté quatre fois le tournoi du Queen\'s tout comme Lleyton Hewitt, Andy Roddick et John McEnroe.'),
(11, 'Murray', 'Andy', 'Sir Andrew Barron Murray, dit Andy Murray, est un joueur professionnel de tennis écossais né le 15 mai 1987 à Glasgow.\r\n\r\nIl a remporté quarante-six titres ATP en simple messieurs, dont trois titres du Grand Chelem, un Masters, deux médailles d\'or olympiques et quatorze Masters 1000.\r\n\r\nFinaliste de l\'US Open en 2008, mais aussi de l\'Open d\'Australie en 2010, 2011, 2013, 2015 et 2016, de Wimbledon en 2012 et de Roland-Garros en 2016, Murray devient le premier joueur britannique, depuis Fred Perry en 1936, à s\'imposer dans un tournoi majeur, au terme de l\'US Open 2012. Il remporte également le tournoi de Wimbledon à deux reprises, en 2013 et 2016, et conquiert le Masters cette même année, devenant ainsi, le 7 novembre 2016, le vingt-sixième numéro 1 mondial à l\'ATP World Tour et le premier joueur britannique au sommet de ce classement. Il achève la saison à ce rang et sera alors sacré champion du monde par l\'ITF.'),
(12, 'Nalbandian', 'David', 'David Pablo Nalbandian, né le 1er janvier 1982 à Córdoba (précisément à Unquillo dans le Grand Córdoba), est un joueur argentin de tennis d\'origine arménienne et italienne1, professionnel entre 2000 et 2013.\r\n\r\nIl a remporté onze titres sur le circuit ATP, dont le Masters en 2005, ainsi que deux Masters 1000, à Madrid puis à Paris-Bercy en 2007.\r\n\r\nConsidéré comme l\'un des joueurs les plus doués de sa génération 2’3’4, il a également été finaliste du tournoi de Wimbledon en 2002, demi-finaliste de l\'US Open en 2003, de l\'Open d\'Australie en 2006, et de Roland-Garros en 2004 et 2006, faisant de lui le seul joueur Argentin de l\'histoire à être entré dans le dernier carré de chaque tournoi du Grand Chelem 5, et le seul à avoir rallié une finale à Wimbledon.'),
(13, 'Cilic', 'Marin', 'Marin Čilić ([marin tʃilitɕ]), né le 28 septembre 1988 à Međugorje en Yougoslavie, est un joueur de tennis croate, professionnel depuis 2005.\r\n\r\nServeur puissant, il a remporté dix-huit titres en simple sur le circuit ATP dont l\'US Open en 2014. En remportant ce titre, il atteint la 8e place au classement ATP, et devient le second joueur croate à gagner un tournoi du Grand Chelem après son entraîneur d\'alors, Goran Ivanišević.'),
(14, 'Tomic', 'Bernard', 'Bernard Tomic (en serbo-croate Bernard Tomić), né le 21 octobre 1992 à Stuttgart, est un joueur de tennis professionnel australien.\r\n\r\nIl était considéré comme l\'un des plus grands espoirs de son sport1,2,3. Né en Allemagne et issu d\'une famille originaire de Croatie et Bosnie4, il émigre en Australie à l\'âge de trois ans et demi. Il est le seul joueur à avoir gagné l\'Orange Bowl dans trois catégories d\'âge différentes et est le plus jeune joueur de l\'histoire titré dans un tournoi du Grand Chelem junior5.\r\n\r\n'),
(15, 'Ferrer', 'David', 'David Ferrer Ern, né le 2 avril 1982 à Jávea (Alicante), est un joueur de tennis espagnol.\r\n\r\nProfessionnel de 2000 à 2019, il a remporté 27 titres en simple sur le circuit ATP dont le Masters 1000 de Paris-Bercy en 2012 ainsi que 10 tournois ATP 500. Il est en 2017 parmi les joueurs n\'ayant jamais remporté de tournoi du Grand Chelem celui qui a remporté le plus de tournois. Son meilleur résultat en tournoi du Grand Chelem est une finale à Roland Garros en 2013 perdue face à Rafael Nadal. Il a également remporté trois Coupe Davis avec l\'équipe d\'Espagne et a été finaliste au Masters en 2007. En juillet 2013, à 31 ans, il atteint la troisième place au classement ATP.'),
(16, 'Rochus', 'Olivier', 'Olivier Rochus, né le 18 janvier 1981 à Namur, est un joueur de tennis belge, professionnel de 1999 à 2014.'),
(17, 'del Potro', 'Juan Martín', 'Juan Martín del Potro, né le 23 septembre 1988 à Tandil, est un joueur de tennis argentin, professionnel depuis 2005.\r\n\r\nIl a remporté vingt-deux titres en simple sur le circuit ATP, dont l\'US Open en 2009 et le Masters 1000 d\'Indian Wells en 2018, et atteint treize autres finales. Il est le troisième joueur argentin à gagner un tournoi du Grand Chelem, après Guillermo Vilas et Gastón Gaudio. Il a atteint la quatrième place mondiale en 2010 puis la troisième en 2018. Il est membre de l\'équipe d\'Argentine de Coupe Davis, avec laquelle il a remporté le titre en 2016. Il a également remporté deux médailles olympiques : la médaille de bronze aux Jeux olympiques de Londres en 2012 face à Novak Djokovic, puis la médaille d\'argent aux Jeux olympiques de Rio en 2016.'),
(18, 'Karlović', 'Ivo', 'Ivo Karlović, né le 28 février 1979 à Zagreb, est un joueur de tennis croate, professionnel depuis 2000.\r\n\r\nSurnommé le « Géant croate » ou « Dr Ivo », il est, avec ses 2,11 m, le plus grand joueur du circuit ATP, et, avec ses 42ans, l\'un des plus vieux. Il a remporté huit tournois ATP en simple sur un total de 19 finales disputées et atteint un quart de finale à Wimbledon en 2009.'),
(19, 'Berdych', 'Tomas', 'Tomáš Berdych Écouter, né le 17 septembre 1985 à Valašské Meziříčí, est un joueur de tennis tchèque, professionnel entre 2002 et 2019.\r\n\r\nIl a remporté treize titres en simple sur le circuit ATP dont le Masters 1000 de Paris-Bercy en 2005. Sa meilleure performance dans un tournoi du Grand Chelem est une finale à Wimbledon en 2010, perdue face à l\'Espagnol Rafael Nadal.\r\n\r\nIl a également remporté la Coupe Davis avec Radek Štěpánek en 2012 et 2013.'),
(20, 'López', 'Feliciano', 'Feliciano López Díaz-Guerra, né le 20 septembre 1981 à Tolède, est un joueur espagnol de tennis professionnel.\r\n\r\nPassé professionnel en 1997, il a remporté sept titres en simple, dont trois tournois de catégorie 500 Series à Vienne en 2007 et au Queen\'s en 2017 et en 2019. Il a aussi gagné cinq titres en double, dont Roland-Garros en 2016. Il a remporté la Coupe Davis à cinq reprises (2004, 2008, 2009, 2011 et 2019). Son meilleur classement en simple est la 12e place mondiale, obtenue le 2 mars 2015 à l\'âge de trente-trois ans.'),
(21, 'Nishikori', 'Kei', 'Kei Nishikori (錦織圭, Nishikori Kei?), né le 29 décembre 1989 à Matsue, est un joueur de tennis japonais. Professionnel depuis 2007, il est le premier joueur japonais de l\'histoire à atteindre la finale d\'un tournoi du Grand Chelem (à l\'US Open en 2014) et la quatrième place au classement ATP (en 2015). Il a remporté douze titres en simple sur le circuit ATP dont six tournois ATP 500. Il a également gagné une médaille de bronze olympique aux Jeux de Rio en 2016.'),
(22, 'Dolgopolov', 'Alexandr', 'Alexandr Dolgopolov (anciennement Oleksandr Dolgopolov Jr., en ukrainien : Олександр Олександрович Долгополов), né le 7 novembre 1988 à Kiev (alors en URSS), est un joueur de tennis professionnel ukrainien.\r\n\r\nIl est droitier et sa surface de prédilection est la terre battue.\r\nEn 2011, il se fait connaître du grand public en atteignant les quarts de finale de l\'Open d\'Australie, après avoir éliminé Jo-Wilfried Tsonga et Robin Söderling.'),
(23, 'Baghdatís', 'Márcos', 'Márcos Baghdatís (en grec : Μάρκος Παγδατής / Márkos Pagdatís), né le 17 juin 1985 à Limassol (Chypre), est un joueur de tennis chypriote, professionnel depuis 2003.\r\n\r\nIl a atteint la finale de l\'Open d\'Australie 2006 au cours de laquelle il s\'est incliné face à Roger Federer.'),
(24, 'Isner', 'John', 'John Isner, né le 26 avril 1985 à Greensboro, est un joueur de tennis américain. Joueur professionnel depuis 2007, il a remporté quinze titres sur le circuit ATP, dont le Masters 1000 de Miami en 2018 lors duquel il bat Alexander Zverev en finale et cinq titres au tournoi d\'Atlanta. Il a perdu treize autres finales dont quatre en Masters 1000 : à Indian Wells en 2012, à Cincinnati en 2013, à Paris-Bercy en 2016 et à Miami en 2019.\r\n\r\nSon meilleur résultat en tournoi du Grand Chelem est une demi-finale à Wimbledon en 2018.'),
(25, 'Söderling', 'Robin', 'Robin Bo Carl Söderling, né le 14 août 1984 à Tibro (Suède), est un joueur de tennis suédois, professionnel de 2001 à 20151.\r\n\r\nIl a remporté dix titres en simple sur le circuit ATP, dont le Masters de Paris-Bercy en 2010, année durant laquelle il a occupé la 4e place du classement mondial. En Grand Chelem, il a notamment atteint à deux reprises la finale de Roland-Garros en 2009 et 2010, s\'inclinant respectivement contre Roger Federer puis Rafael Nadal. En 2009, il se distingue en battant en huitièmes de finale le quadruple tenant du titre Rafael Nadal, devenant le premier joueur à battre l\'Espagnol à Roland-Garros (et l\'un des deux seuls avec Novak Djokovic en 2015).'),
(26, 'Medvedev', 'Daniil', 'Daniil Medvedev, né le 11 février 1996 à Moscou, est un joueur de tennis russe, professionnel depuis 2014.\r\n\r\nIl comptabilise dix titres sur le circuit ATP dont le Masters en 2020 et trois Masters 1000. Son meilleur résultat en Grand Chelem est une finale lors de l\'édition 2019 de l\'US Open où il s\'incline en cinq sets face à Rafael Nadal et une finale à l\'Open d\'Australie 2021 où il s\'incline en trois sets face à Novak Djokovic. Il remporte la deuxième édition de l\'ATP Cup avec l\'équipe de Russie en 2021.'),
(27, 'Goffin', 'David', 'David Goffin, né le 7 décembre 1990 à Rocourt (Liège) en Belgique, est un joueur de tennis belge, professionnel depuis 2008.\r\n\r\nIl a remporté cinq tournois en simple et un en double sur le circuit ATP et a atteint trois quarts de finale en Grand Chelem à Roland-Garros en 2016, à l\'Open d\'Australie en 2017 année où il atteint la finale du Masters après avoir battu Rafael Nadal et Roger Federer, respectivement numéros 1 et 2 mondiaux, ainsi qu\'à Wimbledon en 2019.'),
(28, 'Zverev', 'Alexander', 'Alexander Zverev, né le 20 avril 1997 à Hambourg, est un joueur de tennis professionnel allemand.\r\n\r\nSur le circuit junior, il s\'illustre en 2013 en étant finaliste des Internationaux de France de tennis 2013 et champion du monde la même année. En 2014, il remporte l\'Open d\'Australie en simple garçons.\r\n\r\nIl intègre le circuit professionnel ATP en 2013 et remporte son premier titre en simple en 2016, à Saint-Pétersbourg. Il a remporté trois tournois Masters 1000 : à Rome et à Montréal en 2017 en battant respectivement en finale Novak Djokovic et Roger Federer, puis à Madrid en 2018 contre Dominic Thiem, ainsi que les Masters 2018, en battant Novak Djokovic, numéro 1 mondial, en finale après avoir sorti Roger Federer en demi-finale.'),
(29, 'Thiem', 'Dominic', 'Dominic Thiem, né le 3 septembre 1993 à Wiener Neustadt, est un joueur de tennis autrichien professionnel depuis 2012.\r\n\r\nIl a remporté dix-sept titres en simple sur le circuit ATP et atteint la 3e place mondiale. En 2020, il remporte son premier titre du Grand Chelem à l\'US Open.'),
(30, 'Shapovalov ', 'Denis', 'Denis Shapovalov, né le 15 avril 1999 à Tel Aviv, est un joueur de tennis canadien, professionnel depuis 2016.\r\n\r\n'),
(31, 'Tsitsipás', 'Stéfanos', 'Stéfanos Tsitsipás (grec moderne : Στέφανος Τσιτσιπάς), né le 12 août 1998 à Athènes, est un joueur de tennis grec, professionnel depuis 2015.\r\n\r\nPremier joueur grec à entrer dans le top 100 en 2017, il a remporté cinq tournois ATP en simple dont le Masters en 2019. Dans les tournois du Grand Chelem, il a atteint les demi-finales de l\'Open d\'Australie 2019, de Roland-Garros 2020 et de l\'Open d\'Australie 2021.'),
(32, 'Messi', 'Lionel', 'Lionel Messi, parfois surnommé Leo Messi, né le 24 juin 1987 à Rosario en Argentine, est un footballeur international argentin évoluant au poste d\'attaquant au FC Barcelone.\r\n\r\nSeul footballeur sextuple Ballon d\'or et Soulier d\'or européen, Messi est considéré comme l\'un des meilleurs joueurs de football de l\'histoire. Joueur le plus décisif du xxie siècle, il est élu meilleur ailier droit de tous les temps par France Football tandis que l\'IFFHS le désigne meilleur joueur de la décennie de 2011 à 2020.'),
(33, 'Suarez ', 'Luis', 'Luis Alberto Suárez Díaz, né le 24 janvier 1987 à Salto en Uruguay, est un footballeur international uruguayen évoluant au poste d\'attaquant à l\'Atlético de Madrid.\r\n\r\nFormé dans son pays natal, il remporte à dix-huit ans le championnat d\'Uruguay avec le Nacional avant de rejoindre le championnat des Pays-Bas. Recruté par l\'Ajax Amsterdam en 2007, il termine meilleur buteur du championnat en 2010 puis sacré champion en 2011.\r\n\r\nTransféré au Liverpool FC, il remporte la Coupe de la Ligue en 2012 et termine meilleur buteur du championnat d\'Angleterre en 2014 et remporte le Soulier d\'or européen.'),
(34, 'Luis Nazário de Lima', 'Ronaldo', 'Ronaldo Luís Nazário de Lima, dit Ronaldo, né le 22 septembre 1976 à Bento Ribeiro, un quartier de Rio de Janeiro, est un footballeur international brésilien, qui évoluait au poste d\'avant-centre.\r\n\r\nIl commence sa carrière professionnelle au Brésil, à Cruzeiro, avant de partir ensuite pour l\'Europe et le PSV Eindhoven. Il y reste deux saisons avant de signer pour le FC Barcelone pour un séjour d\'une saison. Ronaldo est ensuite recruté par l\'Inter Milan lors d\'un transfert record. Il reste cinq saisons en Serie A. Après la Coupe du monde 2002, il rejoint les « Galactiques » du Real Madrid pour 42 millions d\'euros. Après cinq saisons avec le club madrilène, il rejoint le Milan AC. En 2009, il retourne dans son pays natal et il est transféré aux Corinthians, club dans lequel il joue ses derniers matchs. Il annonce sa retraite le 14 février 2011.'),
(35, 'Ramos', 'Sergio', 'Sergio Ramos García, né le 30 mars 1986 à Camas en Andalousie, est un footballeur international espagnol qui joue actuellement pour le Real Madrid et l\'équipe d\'Espagne au poste de défenseur central.\r\n\r\nSous le maillot de sa sélection nationale, il remporte l\'Euro 2008, la Coupe du monde 2010 et l\'Euro 2012 en tant que titulaire, faisant donc partie des sept joueurs présents sur le terrain lors de ces trois finales remportées consécutivement pour une triple couronne inédite dans l\'histoire du football mondial. Il est par ailleurs actuellement le joueur le plus capé de la sélection espagnole devant Iker Casillas.\r\n\r\nIl est actuellement le capitaine du Real Madrid et de l\'Espagne. Il porte le brassard de capitaine du Real Madrid depuis le départ en 2015 de l’ancien capitaine et coéquipier en sélection Iker Casillas au FC Porto. Le 19 juillet 2020, il entre dans l\'histoire en ayant marqué 11 buts en une saison en Liga, faisant partie des rares défenseurs ayant marqué plus de 10 buts en Liga depuis Ronald Koeman en 1994 avec 11 réalisations, et le premier au xxie siècle'),
(36, 'Modrić', 'Luka', 'Luka Modrić, né le 9 septembre 1985 à Zadar en Yougoslavie (aujourd\'hui en Croatie), est un footballeur international croate. Il évolue au poste de milieu de terrain au Real Madrid. Il est, avec Davor Šuker et Bernard Vukas, considéré comme l\'un des plus grands joueurs croates de l\'histoire.\r\n\r\nIl commence au Dinamo Zagreb en 2003, élu meilleur espoir croate en 2004, il devient un joueur phare du championnat de Croatie qu\'il remporte trois fois d\'affilée de 2006 à 2008 avant de s\'envoler vers Tottenham fin 2008 où il deviendra l\'un des milieux les plus reconnus de Premier League.'),
(37, 'Ronaldo', 'Cristiano', 'Cristiano Ronaldo dos Santos Aveiro, couramment appelé Ronaldo ou Cristiano Ronaldo et surnommé CR7, né le 5 février 1985 à Funchal, est un footballeur international portugais qui évolue au poste d\'attaquant à la Juventus FC.\r\n\r\nConsidéré comme l\'un des meilleurs joueurs de l\'histoire de son sport, il est le seul footballeur avec Lionel Messi à avoir remporté le Ballon d\'or au moins cinq fois : en 2008, 2013, 2014, 2016 et en 2017. Auteur de plus de 770 buts en carrière, il est le meilleur buteur de la Ligue des champions de l\'UEFA, des coupes d\'Europe, du Real Madrid, du derby madrilène, de la Coupe du monde des clubs de la FIFA et de la sélection portugaise, dont il est le capitaine depuis 2007. Premier joueur à avoir remporté le Soulier d\'or européen à quatre reprises, il est également le co-meilleur buteur de l\'histoire du championnat d\'Europe des nations avec Michel Platini et détient, depuis le 20 juin 2018, le record de buts pour un joueur européen en équipe nationale en dépassant le Hongrois Ferenc Puskás, avec 85 réalisations au moment du record (103 actuellement) 2.'),
(38, 'Henry', 'Thierry', 'Thierry Henry, né le 17 août 1977 aux Ulis (France), est un ancien footballeur international français qui a évolué au poste d\'attaquant entre 1994 et 2014.\r\n\r\nDurant sa jeunesse, il évolue dans plusieurs clubs de la région parisienne avant d\'intégrer le centre de préformation de l\'INF Clairefontaine. Il est ensuite repéré par l\'AS Monaco avec lequel il continue sa formation avant de débuter au niveau professionnel en 1994. Après avoir été sacré champion de France en 1997, poussé par son père, il tente l\'aventure à l\'étranger dans le club de la Juventus. Insatisfait, il quitte le club italien au bout de six mois pour s\'affirmer dans le championnat d\'Angleterre chez les Gunners d\'Arsenal durant huit saisons, avec qui il remporte deux fois le championnat national. Il est élu là-bas Joueur de l\'année à 2 reprises (pour les saisons 2002-2003 et 2003-2004).'),
(39, 'Griezmann', 'Antoine', 'Antoine Griezmann (prononcer : [ɡʁjɛzman]4), surnommé « Grizi », « Grizou » ou encore « Petit Prince » par ses fans et coéquipiers, né le 21 mars 1991 à Mâcon, en Saône-et-Loire, est un footballeur international français. Il évolue dans le championnat d\'Espagne au poste'),
(40, 'da Silva Santos Júnior', 'Neymar', 'Neymar da Silva Santos Júnior, dit Neymar Jr., plus couramment appelé Neymar, né le 5 février 1992 à Mogi das Cruzes (Brésil, État de São Paulo), est un footballeur international brésilien qui évolue au poste d\'attaquant au Paris Saint-Germain. Il est également le capitaine de l\'équipe nationale du Brésil depuis 2014.\r\n\r\nIl est considéré comme l\'un des plus grands joueur du football brésilien et mondial. Il est ainsi élu meilleur joueur sud-américain de l\'année en 2011 et 2012. Neymar est classé dixième au classement du Ballon d\'or 2011, treizième en 2012 puis cinquième en 2013 et en 2016. Il remporte par ailleurs le Bola de Ouro du meilleur joueur du championnat brésilien en 2011.\r\n\r\nNeymar rejoint le club de Santos en 2003. Il évolue dans les équipes de jeunes jusqu\'en 2009, date à laquelle il rejoint l\'équipe fanion. Avec ce club, Neymar remporte la Coupe du Brésil, deux championnats de l\'État de São Paulo, la Recopa Sudamericana et la Copa Libertadores. Il rejoint en 2013 le FC Barcelone, en Espagne, avec lequel il remporte notamment le Championnat d\'Espagne et la Ligue des champions en 2015. Fort d\'une bonne année 2015 avec son club aussi bien collectivement qu\'individuellement, Neymar figure dans la liste des trois finalistes du Ballon d\'or 2015 aux côtés de Cristiano Ronaldo et Lionel Messi, et est donc le premier joueur brésilien à figurer dans cette liste depuis 2007 et son vainqueur Kaká. Il affirme donc les espoirs placés en lui et s\'impose comme l\'un des meilleurs attaquants de sa génération.');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `sportifs`
--
ALTER TABLE `sportifs`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `sportifs`
--
ALTER TABLE `sportifs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
